### PR TITLE
fixing SED-ML documentation; adding parsing to extract variables and observables from simulation configuration

### PR DESCRIPTION
**Pull request by jonrkarr**

### CODE REVIEW

**Comment by dilawar** [comment]
I need to fix the failing CI tests. They test the released wheels that were just uploaded. Looks like it takes a while for new wheels on PyPi to be available.

**Comment by jonrkarr** [comment]
Yes, I know it takes a few minutes for posted wheels to become available.

**Comment by jonrkarr** [comment]
@dilawar, could you merge this?

This introduces more functionality for BioSimulators. It doesn't conflict with the main part of the Smoldyn package.

**Comment by jonrkarr** [comment]
Thanks!

**Pull request merged**
