### PR TITLE
CI support for tag

### PR DESCRIPTION
**Pull request by dilawar**
Currently, when a  tag vX.Y is created, the build on github actions __does not__ set the version to X.Y. This has to be done manually in top-level CMakeFilelist.txt.

This PR add an experimental feature: if the commit is tagged `v.X.Y`, for that particular commit, the version is set to `X.Y` and pypi should get a release `X.Y` on successful merge. 

To test this PR, tag the commit `v2.65.1` etc after merging.

### CODE REVIEW

**Comment by dilawar** [comment]
@ssandrews I use `black` (https://pypi.org/project/black/) tool to format the python code. If you change python code, just run `black filename.py` to auto-format the code to keep the format consistent.

Similarly, i use `clang-format` for cpp files but I am not too worried about cpp format consistency across files.

**Comment by ssandrews** [comment]
Thanks for the information about the formatting tools.

I just made a trivial update to the documentation, and committed it. Then,
I tagged the latest version as 2.64.1, to test the new system. Let me know
if things are working as desired.

By the way, I changed the main CMakeLists.txt file recently by removing a
line about version numbers, because it interfered with the ability to
assign version numbers on the command line as a CMake option (with
-DSMOLDYN_VERSION).

**Comment by dilawar** [comment]
Hi Steve,

I see. I have prepare a new PR which honors SMOLDYN_VERSION. For a tag, the
version needs to be fixed as 2.64.1 etc. in the CMakeLists.txt else the
wheel will be uploaded to development channel.  Currently, when we tag a
commit by v2.64.x the wheel has the version 2.64dev-DATEOFBUILD which is a
development release.

Another way around it that I tweak the github action files and change the
build process for the tags.

best,
   Dilawar

Dilawar Singh, Ph.D.
LinkedIn <https://www.linkedin.com/in/dilawar-singh-ph-d-44b81b194/> ORCID
<https://orcid.org/0000-0002-4645-3211> Github <https://github.com/dilawar>

**Comment by ssandrews** [comment]
Hi Dilawar,

I'm not sure that I fully understand the changes, but I just deleted tag
2.64.1 and created tag 2.64.2, so hopefully that will work correctly.

Thanks,
-Steve

**Pull request merged**
